- id: https://doi.org/10.1038/s41467-022-33319-4
  image: ../images/papers/Olave2022.png

- id: https://doi.org/10.1073/pnas.2202862119
  image: ../images/papers/Wooldridge2022.png

- id: https://doi.org/10.1098/rspb.2022.0266
  image: ../images/papers/Torres2022.png

- id: https://doi.org/10.1111/mec.16466
  image: ../images/papers/Nacif2022.png

- id: https://doi.org/10.1002/ece3.8751
  image: ../images/papers/Kratochwil2022b.png

- id: https://doi.org/10.1038/s41467-021-27685-8
  image: ../images/papers/Kratochwil2022.png

- id: https://doi.org/10.1111/mec.16066
  image: ../images/papers/Comeault2021.png

- id: https://doi.org/10.1038/s41586-021-03451-0
  image: ../images/papers/Rhie2021.png

- id: https://doi.org/10.1038/s41467-021-21379-x
  image: ../images/papers/Li2021.png

- id: https://doi.org/10.1111/mec.15774
  image: ../images/papers/Xiong2021.png

- id: https://doi.org/10.1038/s41586-020-2845-0
  image: ../images/papers/Kautt2020.png

- id: doi:10.1093/molbev/msaa118
  image: ../images/papers/Franchini2020.png

- id: https://doi.org/10.1098/rspb.2020.0969
  image: ../images/papers/Torres2020.png

- id: https://doi.org/10.1111/mec.15304
  image: ../images/papers/Raffini2020.png

- id: https://doi.org/10.1002/evl3.64
  image: ../images/papers/Kautt2018.png

- id: https://doi.org/10.1111/mec.14077
  image: ../images/papers/Franchini2017.png

- id: https://doi.org/10.1111/mec.14029
  image: ../images/papers/Machado2017.png

- id: https://doi.org/10.1002/ece3.2287
  image: ../images/papers/Kautt2016b.png

- id: https://doi.org/10.1371/journal.pgen.1006157
  image: ../images/papers/Kautt2016a.png

- id: https://doi.org/10.1111/mec.13461
  image: ../images/papers/Kavembe2016.png

- id: https://doi.org/10.1186/s12862-015-0287-3
  image: ../images/papers/Machado2015.png

- id: https://doi.org/10.1038/ncomms6168
  image: ../images/papers/Elmer2014.png

- id: https://doi.org/10.1093/OBO/9780199941728-0053
  image: ../images/papers/MeyerKautt2014.png

- id: doi:10.1111/bij.12271
  image: ../images/papers/Torres2014.png

- id: https://doi.org/10.1111/j.1365-294X.2012.05738.x
  image: ../images/papers/Kautt2012.png

- id: https://doi.org/10.1186/1741-7007-8-60
  image: ../images/papers/Elmer2010.png
